<?php

namespace App\Exports;

use App\Models\Transaction;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnFormatting;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;

class AdminTransactionsExport implements FromCollection, WithHeadings, WithMapping, ShouldAutoSize, WithStyles, WithColumnFormatting
{
    public function collection()
    {
        return Transaction::with(['user', 'stock'])
            ->orderBy('created_at', 'desc')
            ->get();
    }

    public function headings(): array
    {
        $admin = Auth::user();

        return [
            // Baris 1: Judul Laporan
            ['TRADEINK ALL TRANSACTIONS REPORT'],
            // Baris 2: Info Admin
            ['Generated by Admin: ' . $admin->name],
            // Baris 3: Tanggal Export
            ['Date: ' . now()->format('d M Y, H:i')],
            // Baris 4: Spacer
            [],
            // Baris 5: Header Tabel
            [
                'DATE',
                'USER NAME',
                'USER EMAIL',
                'TYPE',
                'STOCK SYMBOL',
                'QUANTITY',
                'PRICE (USD)',
                'TOTAL VALUE (USD)',
                'STATUS'
            ]
        ];
    }

    public function map($transaction): array
    {
        return [
            $transaction->created_at->format('Y-m-d H:i:s'),
            $transaction->user->name ?? 'Deleted User',
            $transaction->user->email ?? '-',
            strtoupper($transaction->type),
            $transaction->stock ? $transaction->stock->symbol : '-',
            $transaction->qty,
            $transaction->price,
            $transaction->total,
            strtoupper($transaction->status),
        ];
    }

    public function columnFormats(): array
    {
        return [
            'F' => '#,##0.0000', // Quantity
            'G' => NumberFormat::FORMAT_CURRENCY_USD_SIMPLE, // Price
            'H' => NumberFormat::FORMAT_CURRENCY_USD_SIMPLE, // Total
        ];
    }

    public function styles(Worksheet $sheet)
    {
        $highestRow = $sheet->getHighestRow();
        $highestColumn = 'I'; // Kolom terakhir (Status)

        // --- A. STYLING HEADER LAPORAN (Baris 1-3) ---

        $sheet->mergeCells('A1:I1');
        $sheet->mergeCells('A2:I2');
        $sheet->mergeCells('A3:I3');

        // Style Judul Utama
        $sheet->getStyle('A1')->applyFromArray([
            'font' => [
                'bold' => true,
                'size' => 16,
                'color' => ['argb' => 'FF1F2937'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
            ],
        ]);

        // Style Info
        $sheet->getStyle('A2:A3')->applyFromArray([
            'font' => [
                'size' => 11,
                'color' => ['argb' => 'FF4B5563'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_LEFT,
            ],
        ]);

        // --- B. STYLING TABEL DATA (Mulai Baris 5) ---

        // Style Header Tabel
        $sheet->getStyle("A5:{$highestColumn}5")->applyFromArray([
            'font' => [
                'bold' => true,
                'color' => ['argb' => 'FFFFFFFF'],
                'size' => 12,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['argb' => 'FF1F2937'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
        ]);

        // Style Border & Vertical Align
        $sheet->getStyle("A5:{$highestColumn}{$highestRow}")->applyFromArray([
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['argb' => 'FFD1D5DB'],
                ],
            ],
            'alignment' => [
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
        ]);

        // Alignment Data Spesifik (Mulai Baris 6)
        if ($highestRow >= 6) {
            // Center: Date (A), Type (D), Symbol (E), Status (I)
            $sheet->getStyle("A6:A{$highestRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("D6:E{$highestRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("I6:I{$highestRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

            // Right: Qty (F), Price (G), Total (H)
            $sheet->getStyle("F6:H{$highestRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        }

        return [];
    }
}
