<?php

namespace App\Exports;

use App\Models\Stock;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

class StocksExport implements FromCollection, WithHeadings, WithMapping, ShouldAutoSize, WithStyles
{
    public function collection()
    {
        return Stock::all();
    }

    public function headings(): array
    {
        $admin = Auth::user();

        return [
            // Baris 1: Judul Laporan
            ['TRADEINK STOCKS LIST'],
            // Baris 2: Info Admin
            ['Generated by Admin: ' . $admin->name],
            // Baris 3: Tanggal Export
            ['Date: ' . now()->format('d M Y, H:i')],
            // Baris 4: Spacer
            [],
            // Baris 5: Header Tabel
            [
                'SYMBOL',
                'NAME',
                'CURRENCY',
                'VISIBLE',
                'CREATED AT'
            ]
        ];
    }

    public function map($stock): array
    {
        return [
            $stock->symbol,
            $stock->name,
            $stock->currency,
            $stock->is_visible ? 'YES' : 'NO',
            $stock->created_at->format('Y-m-d H:i'),
        ];
    }

    public function styles(Worksheet $sheet)
    {
        $highestRow = $sheet->getHighestRow();
        $highestColumn = 'E'; // Kolom terakhir (Created At)

        // --- A. STYLING HEADER LAPORAN (Baris 1-3) ---

        $sheet->mergeCells('A1:E1');
        $sheet->mergeCells('A2:E2');
        $sheet->mergeCells('A3:E3');

        // Style Judul Utama
        $sheet->getStyle('A1')->applyFromArray([
            'font' => [
                'bold' => true,
                'size' => 16,
                'color' => ['argb' => 'FF1F2937'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
            ],
        ]);

        // Style Info
        $sheet->getStyle('A2:A3')->applyFromArray([
            'font' => [
                'size' => 11,
                'color' => ['argb' => 'FF4B5563'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_LEFT,
            ],
        ]);

        // --- B. STYLING TABEL DATA (Mulai Baris 5) ---

        // Style Header Tabel
        $sheet->getStyle("A5:{$highestColumn}5")->applyFromArray([
            'font' => [
                'bold' => true,
                'color' => ['argb' => 'FFFFFFFF'],
                'size' => 12,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['argb' => 'FF1F2937'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
        ]);

        // Style Border & Vertical Align
        $sheet->getStyle("A5:{$highestColumn}{$highestRow}")->applyFromArray([
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['argb' => 'FFD1D5DB'],
                ],
            ],
            'alignment' => [
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
        ]);

        // Alignment Data Spesifik (Mulai Baris 6)
        if ($highestRow >= 6) {
            // Center: Symbol (A), Currency (C), Visible (D), Date (E)
            $sheet->getStyle("A6:A{$highestRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("C6:E{$highestRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

            // Left: Name (B) - Biarkan default (biasanya left untuk string)
            $sheet->getStyle("B6:B{$highestRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_LEFT);
        }

        return [];
    }
}
