<!DOCTYPE html>
<html>

<head>
    <title>All Transactions Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #0f172a;
            color: white;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .meta {
            margin-bottom: 10px;
            font-size: 12px;
        }

        .badge-buy {
            color: green;
        }

        .badge-sell {
            color: red;
        }
    </style>
</head>

<body>
    <div class="header">
        <h2>TradeInk - All Transactions Report</h2>
        <p>Generated by Admin: {{ auth()->user()->name }}</p>
        <p>Date: {{ now()->format('d M Y, H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>User</th>
                <th>Type</th>
                <th>Symbol</th>
                <th>Qty</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $t)
            <tr>
                <td>{{ $t->created_at->format('Y-m-d H:i') }}</td>
                <td>
                    <strong>{{ $t->user->name ?? 'N/A' }}</strong><br>
                    <span style="color: #666;">{{ $t->user->email ?? '-' }}</span>
                </td>
                <td>
                    <span class="{{ $t->type === 'buy' ? 'badge-buy' : 'badge-sell' }}">
                        {{ ucfirst($t->type) }}
                    </span>
                </td>
                <td>{{ $t->stock ? $t->stock->symbol : '-' }}</td>
                <td>{{ $t->qty }}</td>
                <td>${{ number_format($t->price, 2) }}</td>
                <td>${{ number_format($t->total, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>